app/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'


urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>/', views.UserActivateView.as_view(), name='user_activate'),
    path('my-profile/', views.UserProfileView.as_view(), name='my_profile'),
 ]

app/currency/urls.py
from django.urls import path
from currency import views

app_name = 'currency'


urlpatterns = [

    path('contactus/list/', views.ContactUsView.as_view(), name='contactus'),
    path('contactus/create/', views.ContactUsCreateView.as_view(), name='contactus_create'),

    path('rate/list/', views.RateListView.as_view(), name='rate_list'),
    path('rate/create/', views.RateCreateView.as_view(), name='rate_create'),
    path('rate/update/<int:pk>', views.RateUpdateView.as_view(), name='rate_update'),
    path('rate/delete/<int:pk>', views.RateDeleteView.as_view(), name='rate_delete'),
    path('rate/details/<int:pk>', views.RateDetailsView.as_view(), name='rate_details'),
    path('rate/download/', views.DownloadRateView.as_view(), name='rate_download'),

    path('source/list/', views.SourceListView.as_view(), name='source_list'),
    path('source/create/', views.SourceCreateView.as_view(), name='source_create'),
    path('source/update/<int:pk>', views.SourceUpdateView.as_view(), name='source_update'),
    path('source/delete/<int:pk>', views.SourceDeleteView.as_view(), name='source_delete'),
]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from currency import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('silk/', include('silk.urls', namespace='silk')),
]

app/currency/models.py
from django.db import models
from currency.model_choices import CurrencyType


class ContactUs(models.Model):
    email_from = models.EmailField(max_length=254)
    email_to = models.EmailField(max_length=254)
    subject = models.CharField(max_length=254)
    message = models.CharField(max_length=10000)
    created = models.DateTimeField(auto_now_add=True)


class Source(models.Model):
    source_url = models.CharField(max_length=255)
    name = models.CharField(max_length=64)


class Rate(models.Model):
    base_currency_type = models.CharField(
        max_length=3,
        choices=CurrencyType.choices,
        default=CurrencyType.CURRENCY_TYPE_USD,
    )
    currency_type = models.CharField(max_length=3, choices=CurrencyType.choices)
    sale = models.DecimalField(max_digits=10, decimal_places=4)
    buy = models.DecimalField(max_digits=10, decimal_places=4)
    created = models.DateTimeField(auto_now_add=True)
    source = models.ForeignKey(Source, on_delete=models.CASCADE, null=True, default=None)


class ResponseLog(models.Model):
    response_time = models.FloatField()
    request_method = models.CharField(max_length=64)
    query_params = models.CharField(max_length=1000)
    ip = models.CharField(max_length=255)
    path = models.CharField(max_length=255)

app/currency/forms.py
from django import forms
from currency.models import Rate, Source


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'base_currency_type',
            'currency_type',
            'sale',
            'buy',
            'source',
        )


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            'name',
            'source_url',
        )

app/currency/views.py
import csv
import io

from django.http import HttpResponse, HttpResponseRedirect  # noqa
from django.views import generic
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
# from django.contrib.auth import get_user_model

from currency.models import ContactUs, Rate, Source
from currency.forms import RateForm, SourceForm


class IndexView(generic.TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rate_count'] = Rate.objects.count()
        return context


class ContactUsView(generic.ListView):
    queryset = ContactUs.objects.all()
    template_name = 'contact_us.html'


class ContactUsCreateView(generic.CreateView):
    model = ContactUs
    success_url = reverse_lazy('currency:index')
    template_name = 'contactus_create.html'
    fields = (
        'email_from',
        'subject',
        'message',
    )

    def form_valid(self, form):
        response = super().form_valid(form)

        subject = 'ContactUs From Currency Project'
        message = f'''
        Subject From Client: {self.object.subject}
        Email: {self.object.email_from}
        Wants to contact
        '''

        send_mail(
            subject,
            message,
            settings.EMAIL_HOST_USER,
            [settings.EMAIL_HOST_USER],
            fail_silently=False,
        )

        return response


class RateListView(LoginRequiredMixin, generic.ListView):
    queryset = Rate.objects.all().select_related('source')
    template_name = 'rate_list.html'


class RateCreateView(generic.CreateView):
    queryset = Rate.objects.all()
    template_name = 'rate_create.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')


class RateUpdateView(UserPassesTestMixin, generic.UpdateView):

    def test_func(self):
        """only for superusers"""
        return self.request.user.is_superuser

    queryset = Rate.objects.all()
    template_name = 'rate_update.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')


class RateDeleteView(UserPassesTestMixin, generic.DeleteView):

    def test_func(self):
        """only for superusers"""
        return self.request.user.is_superuser

    queryset = Rate.objects.all()
    template_name = 'rate_delete.html'
    success_url = reverse_lazy('currency:rate_list')


class RateDetailsView(generic.DetailView):
    queryset = Rate.objects.all()
    template_name = 'rate_details.html'


class SourceListView(generic.ListView):
    queryset = Source.objects.all()
    template_name = 'source_list.html'


class SourceCreateView(generic.CreateView):
    queryset = Source.objects.all()
    template_name = 'source_create.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source_list')


class SourceUpdateView(generic.UpdateView):
    queryset = Source.objects.all()
    template_name = 'source_update.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source_list')


class SourceDeleteView(generic.DeleteView):
    queryset = Source.objects.all()
    template_name = 'source_delete.html'
    success_url = reverse_lazy('currency:source_list')


class DownloadRateView(generic.View):

    def get__(self, request):
        with open('rate.csv', 'w', newline='') as csvfile:
            spamwriter = csv.writer(csvfile)
            headers = ['id', 'buy', 'sale']
            spamwriter.writerow(headers)
            for rate in Rate.objects.all():
                row = [
                    rate.id,
                    rate.buy,
                    rate.sale,
                ]
                spamwriter.writerow(row)

        with open('rate.csv', 'r') as f:
            file_data = f.read()

        return HttpResponse(file_data, content_type='text/csv')

    def get(self, request):
        csvfile = io.StringIO()
        spamwriter = csv.writer(csvfile)
        headers = ['id', 'buy', 'sale']
        spamwriter.writerow(headers)
        for rate in Rate.objects.all():
            row = [
                rate.id,
                rate.buy,
                rate.sale,
            ]
            spamwriter.writerow(row)

        csvfile.seek(0)
        return HttpResponse(csvfile.read(), content_type='text/csv')

app/currency/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Currency Rates Project</title>
</head>
<body>

{% include 'parts/navbar.html' %}

{% block main_content %}


{% endblock main_content %}

</body>
</html>

app/currency/templates/contact_us.html
{% extends 'base.html' %}

{% block main_content %}
    <div><a href="{% url 'currency:contactus_create' %}">Contact Us!</a></div>
    <table>
        <th scope="col">ID</th>
        <th scope="col">Email from</th>
        <th scope="col">Email to</th>
        <th scope="col">Subject</th>
        <th scope="col">Message</th>
        <th scope="col">Created</th>
        {% for contact in contactus_list %}
            <tr>
                <td>{{ contact.id }}</td>
                <td>{{ contact.email_from }}</td>
                <td>{{ contact.email_to }}</td>
                <td>{{ contact.subject }}</td>
                <td>{{ contact.message }}</td>
                <td>{{ contact.created }}</td>
            <tr/>
        {% endfor %}
    </table>

{% endblock main_content %}

app/currency/templates/contactus_create.html
{% extends 'base.html' %}

{% block main_content %}
    Contact Us Create

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send</button>
    </form>
{% endblock main_content %}

app/currency/templates/index.html
{%  extends 'base.html' %}

{% block main_content %}

    <div>Currency Exchange Project</div>

    <div>
        Currency Rates List: <a href="{% url 'currency:rate_list' %}">Click Here</a>
    </div>

    <div>Rate count: {{ rate_count }}</div>

    <div>
        Contact us: <a href="{% url 'currency:contactus_create' %}">Click Here</a>
    </div>

    <div>
        Source List: <a href="{% url 'currency:source_list' %}">Click Here</a>
    </div>

{% endblock main_content %}

app/currency/templates/my_profile.html
{%  extends 'base.html' %}

{% block main_content %}
    My Profile

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="reset">Reset</button>
    <button type="submit">Send</button>
    </form>
{% endblock main_content %}

app/currency/templates/rate_create.html
{%  extends 'base.html' %}

{% block main_content %}
    Rate Create

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Send</button>
    </form>
{% endblock main_content %}

app/currency/templates/rate_delete.html
{%  extends 'base.html' %}

{% block main_content %}
    Rate Delete

    <div>Delete object with id {{ object.id }}</div>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>

{% endblock main_content %}

app/currency/templates/rate_details.html
{%  extends 'base.html' %}

{% block main_content %}
    <div> ID: {{ object.id }}</div>
    <div> Buy: {{ object.buy }}</div>
    <div> Sale: {{ object.sale }}</div>

{% endblock main_content %}

app/currency/templates/rate_list.html
{%  extends 'base.html' %}

{% block main_content %}
    <div><a href="{% url 'currency:rate_create' %}">Create new rate</a></div>
    <div><a href="{% url 'currency:rate_download' %}">Download CSV</a></div>
    <table border="1">
        <th scope="col">ID</th>
        <th scope="col">Sale</th>
        <th scope="col">Buy</th>
        <th scope="col">Base type</th>
        <th scope="col">Type</th>
        <th scope="col">Source</th>
        {% for rate in rate_list %}
            <tr>
                <td>{{ rate.id }}</td>
                <td>{{ rate.sale }}</td>
                <td>{{ rate.buy }}</td>
                <td>{{ rate.get_base_currency_type_display }}</td>
                <td>{{ rate.get_currency_type_display }}</td>
                <td>{{ rate.source.name }}</td>
                    <td><a href="{% url 'currency:rate_details' rate.id %}">view details</a></td>
                     {% if request.user.is_superuser %}
                        <td><a href="{% url 'currency:rate_update' rate.id %}">edit</a></td>
                        <td><a href="{% url 'currency:rate_delete' rate.id %}">delete</a></td>
                     {% endif %}
            <tr/>
        {% endfor %}
    </table>

{% endblock main_content %}

app/currency/templates/rate_update.html
{%  extends 'base.html' %}

{% block main_content %}
    Rate Update

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Send</button>
    </form>
{% endblock main_content %}

app/currency/templates/source_create.html
{%  extends 'base.html' %}

{% block main_content %}
    Source Create

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Send</button>
    </form>
{% endblock main_content %}

app/currency/templates/source_delete.html
{%  extends 'base.html' %}

{% block main_content %}
    Source Delete

    <div>Delete source {{ object.id }}</div>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>

{% endblock main_content %}

app/currency/templates/source_list.html
{%  extends 'base.html' %}

{% block main_content %}
    <div><a href="{% url 'currency:source_create' %}">Create new source</a></div>
    <table>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Url</th>
        {% for source in source_list %}
            <tr>
                <td>{{ source.id }}</td>
                <td>{{ source.name }}</td>
                <td>{{ source.source_url }}</td>
                    <td><a href="{% url 'currency:source_update' source.id %}">edit</a></td>
                    <td><a href="{% url 'currency:source_delete' source.id %}">delete</a></td>
            <tr/>
        {% endfor %}
    </table>

{% endblock main_content %}

app/currency/templates/source_update.html
{%  extends 'base.html' %}

{% block main_content %}
    Source Update

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Send</button>
    </form>
{% endblock main_content %}